# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7a71c4963457f2c28a5191b993ecc8e0f4a5149e77da7dee48f67df15545a15a775cb6458f76bb4fc755f06028111398e528a633f52083dbf91dd1a27ae218

test:
  secret_key_base: 028ad1f287838667c7a38880add9b4c708f13c68c2217ce02e10f59cf98d2e9cf9c06767d4057a84c5d2dd2d89bc1ceb20533c221e654a2d15c50464fa7f3ae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
